In [ ]:
import matplotlib.pyplot as plt
import numpy as np
import torch


In [ ]:
data = np.genfromtxt('/content/computer_price.csv',delimiter=',',skip_header=1,dtype=float)
print(data)

[[1100.    4.  280.]
 [1600.    4.  300.]
 [1000.    8.  350.]
 [1500.   32.  500.]
 [2000.    4.  500.]
 [2200.   16.  700.]
 [2600.   32. 1050.]
 [2100.    8.  620.]
 [2400.   12.  780.]
 [3000.    8. 1000.]
 [3200.    8. 1100.]
 [1700.   16.  510.]]


In [ ]:
print(y.shape)

(12, 1)


In [ ]:
x,y=np.hsplit(data,np.array([2]))

In [ ]:
x[:,0]=x[:,0]/100
y/=100

In [ ]:
x_train = torch.tensor(x[:10],dtype=torch.float32)
y_train = torch.tensor(y[:10],dtype=torch.float32)

In [ ]:
x_test = torch.tensor(x[10:],dtype=torch.float32)
y_test = torch.tensor(y[10:],dtype=torch.float32)

In [ ]:
model = torch.nn.Linear(2,1)

In [ ]:
criterion = torch.nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(),lr=0.001)

In [ ]:
epochs = 25
for epoch in range(epochs):
    optimizer.zero_grad()
    y_hat = model(x_train)
    loss = criterion(y_train,y_hat)
    loss.backward()
    optimizer.step()
    print(f'loss: \t {loss.item()}')

loss: 	 26.832576751708984
loss: 	 2.129002094268799
loss: 	 0.7562593221664429
loss: 	 0.6725519299507141
loss: 	 0.6619914770126343
loss: 	 0.657002329826355
loss: 	 0.6534578204154968
loss: 	 0.650833249092102
loss: 	 0.6488798260688782
loss: 	 0.6474233865737915
loss: 	 0.6463321447372437
loss: 	 0.6455116271972656
loss: 	 0.6448915004730225
loss: 	 0.6444188356399536
loss: 	 0.6440553665161133
loss: 	 0.6437723636627197
loss: 	 0.6435493230819702
loss: 	 0.6433703303337097
loss: 	 0.6432238221168518
loss: 	 0.6431015729904175
loss: 	 0.6429961919784546
loss: 	 0.6429051756858826
loss: 	 0.6428229212760925
loss: 	 0.6427484750747681
loss: 	 0.6426789164543152


In [ ]:
x_test

tensor([[32.,  8.],
        [17., 16.]])

In [ ]:
y_hat = model(x_test)
print(y_hat*100)

tensor([[975.0483],
        [563.1902]], grad_fn=<MulBackward0>)
