In [ ]:
import torch

### Create array

# Numerical Python

In [ ]:
def list_arr(list1):
  '''
  Convert list the array
  '''

  return

In [ ]:
list_arr([1,2,3,4])

tensor([1, 2, 3, 4])

In [ ]:
def even_array(lst):
  '''
  Convert only even items to array
  '''
  # CODE
  return 0

In [ ]:
even_array([1,2,3,4,5,6,7,8])

tensor([2, 4, 6, 8])

## PyTorch Tensor properties


In [ ]:
def arry_1D():
  '''
  Create any 1D array
  '''
  lst = []
  # CODE
  return 0

In [ ]:
arry_1D()

tensor([0, 1, 2, 3, 4])

In [ ]:
def arry_2D():
  '''
  Create any 2D array
  '''
  # CODE
  return 0

In [ ]:
arry_2D()

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
def arry_3D():
  '''
  Create any 3D array
  '''
  # CODE
  return 0

In [ ]:
arry_3D().ndim

3

### The shape of the array
 **size**  - Return size of tensor.
 **Returns**: tensor



In [ ]:
def arry_3x3():
  '''
  Create any 3x3 array
  '''
  # CODE
  return 0

In [ ]:
arry_3x3().size()

torch.Size([3, 3])

In [ ]:
def arry_2x3():
  '''
  Create lst to 2x3 array
  return 1D
  '''
  # CODE
  return 0

In [ ]:
arry_2x3().size()

torch.Size([2, 3])

# Creating Arrays

### torch.arange

In [ ]:
def arange_1D_arr():
  '''
  Create any 1D array
  return array
  '''
  # CODE
  return 0

In [ ]:
arange_1D_arr()

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
def arrange_array(n):
  '''
  Create any array from 0 to n
  return array
  '''
  # CODE
  return 0

In [ ]:
arrange_array(5)

tensor([0, 1, 2, 3, 4])

### torch.linspace

In [ ]:
def linspace_arr(n):
  '''
  Create an array of the range 0 and n divided by 10
  return array
  '''
  # CODE
  return 0

In [ ]:
linspace_arr(12)

tensor([ 0.0000,  1.3333,  2.6667,  4.0000,  5.3333,  6.6667,  8.0000,  9.3333,
        10.6667, 12.0000])

### torch.zeros

In [ ]:
def array_zeros_nxm(n,m):
  '''
  Create an nxm array of zeros
  return array
  '''
  # CODE
  return 0

In [ ]:
array_zeros_nxm(2, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
def array_zeros_3D(n, m, ch):
  '''
  Create any an 3D array of zeros
  return 3D array
  '''
  # CODE
  return 0

In [ ]:
array_zeros_3D(5, 5, 3)

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])

### torch.ones

In [ ]:
def array_zeros_nxm(n,m):
  '''
  Create an nxm array of ones
  return array
  '''
  # CODE
  return 0

In [ ]:
array_zeros_nxm(4, 5)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

### torch.full

In [ ]:
def array_full_3D(n,m,k):
  '''
  Create any an 3D array of seven, shape = (n,m,k)
  return 3D array
  '''
  # CODE
  return

In [ ]:
array_full_3D(3, 4, 255)

tensor([[255, 255, 255, 255],
        [255, 255, 255, 255],
        [255, 255, 255, 255]])